### ISSUE TITLE
RobotTrader.exe не запускается, а собранный NTrade.exe показывать логин экран с багами

### ISSUE THREAD

**Issue by VladislavShubnikov** [Lomdjaria1/NeuroTrade#3]
Если взять из архива RobotTrader.exe, и запуситить, то приложение тут же завершит работу, ничего не показав на экране,
Если собрать в Visual Studio проект NTrade.csproj
то при запуске приложение показыват окно со вводом логина-пароля и в этом диалоге управляющие элементы пересекаются друг с другом так что трудно что-то прочитать.
Да. в комментариях к новому состоянию проекта хорошо бы указать тестовый логин-пароль.
![login_screen](https://cloud.githubusercontent.com/assets/25512352/25096771/60fa8d9c-23aa-11e7-9f62-956d32aa58f7.jpg)

**Comment by Lomdjaria1** [comment]
Исправлено. Файл Robottrader изменен. Тестовый логин и пароль указаны и в хелпе и в кратком руководстве по включению
